# Generated by Django 4.1.5 on 2023-01-10 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_identifier', models.CharField(max_length=50)),
                ('tag_name', models.CharField(max_length=50)),
                ('tray_Image_FileLink', models.ImageField(upload_to='')),
                ('tray_Image_FileName', models.CharField(max_length=50)),
                ('sticker_List_size', models.IntegerField()),
                ('premium', models.BooleanField()),
                ('avoid_cache', models.BooleanField()),
                ('publisher_name', models.CharField(blank=True, max_length=50)),
                ('publisher_email', models.EmailField(blank=True, max_length=254)),
                ('publisher_website_zip', models.URLField()),
                ('license_Agreement_Link', models.URLField(blank=True)),
                ('privacy_policy', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCats_id', models.IntegerField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stickerapp.cat')),
            ],
        ),
        migrations.CreateModel(
            name='StickerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker_name', models.CharField(max_length=50)),
                ('sticker_link', models.URLField()),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stickerapp.pack')),
            ],
        ),
        migrations.AddField(
            model_name='pack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stickerapp.user'),
        ),
    ]
