# Generated by Django 4.1.5 on 2023-01-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickerlist',
            name='sticker_link',
        ),
        migrations.AddField(
            model_name='stickerlist',
            name='sticker',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
