# Generated by Django 4.1.5 on 2023-01-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0002_remove_stickerlist_sticker_link_stickerlist_sticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickerlist',
            name='sticker',
            field=models.IntegerField(),
        ),
    ]
