# Generated by Django 4.1.5 on 2023-01-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0005_cat_catname_pack_cat_id_pack_subcats_id_subcats_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='catname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subcats',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
