# Generated by Django 4.1.5 on 2023-01-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0006_alter_cat_catname_alter_subcats_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='catname',
            new_name='cat_name',
        ),
    ]
