# Generated by Django 4.1.5 on 2023-01-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0007_rename_catname_cat_cat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='cat_name',
        ),
        migrations.AddField(
            model_name='cat',
            name='catname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcats',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
