# Generated by Django 4.1.5 on 2023-01-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0009_rename_cat_id_pack_cat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pack',
            old_name='SubCats_id',
            new_name='sub_cats_id',
        ),
    ]
