# Generated by Django 4.1.5 on 2023-01-11 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0014_alter_stickerlist_sticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='subcats',
            name='subCats_id',
        ),
    ]
