# Generated by Django 4.1.5 on 2023-01-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0015_remove_cat_cat_id_remove_subcats_subcats_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('UserName', models.CharField(max_length=70)),
                ('tagidentifier', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='UserName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='pack_identifier',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='tag_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
