# Generated by Django 4.1.5 on 2023-01-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0016_like_user_email_user_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='like',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pack',
            name='tag_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stickerlist',
            name='sticker_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
