# Generated by Django 4.1.5 on 2023-01-13 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0017_delete_like_user_password_alter_pack_tag_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stickerapp.user')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stickerapp.pack')),
            ],
        ),
    ]
