# Generated by Django 4.1.5 on 2023-01-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0021_remove_pack_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='Like', to='stickerapp.user'),
        ),
    ]
