# Generated by Django 4.1.5 on 2023-01-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0027_remove_pack_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='Liked', to='stickerapp.user'),
        ),
    ]
