# Generated by Django 4.1.5 on 2023-01-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0028_pack_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='liked',
        ),
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default='Like', max_length=10),
        ),
    ]
