# Generated by Django 4.1.5 on 2023-01-13 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0029_remove_pack_liked_alter_like_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userId',
        ),
    ]
