# Generated by Django 4.1.5 on 2023-01-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0030_remove_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='publisher_website_zip',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='sticker_list_size',
            field=models.IntegerField(null=True),
        ),
    ]
