# Generated by Django 4.1.5 on 2023-01-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0034_like_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserName',
            new_name='userName',
        ),
        migrations.AlterField(
            model_name='pack',
            name='sticker_list_size',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
