# Generated by Django 4.1.5 on 2023-01-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0035_rename_user_like_user_rename_username_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
