# Generated by Django 4.1.5 on 2023-01-14 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0037_alter_pack_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stickerapp.user'),
        ),
    ]
