# Generated by Django 4.1.5 on 2023-01-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0038_alter_pack_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='tray_image_filelink',
            field=models.ImageField(blank=True, upload_to='stickerstore'),
        ),
    ]
