# Generated by Django 4.1.5 on 2023-01-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0040_remove_like_user_remove_pack_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='SubCats',
            new_name='Sub_Category',
        ),
        migrations.AlterField(
            model_name='pack',
            name='tray_image_filelink',
            field=models.ImageField(blank=True, upload_to='tray_image'),
        ),
    ]
