# Generated by Django 4.1.5 on 2023-01-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0044_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
