# Generated by Django 4.1.5 on 2023-01-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0045_pack_approved_alter_like_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='approved',
        ),
    ]
