# Generated by Django 4.1.5 on 2023-01-17 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stickerapp', '0048_pack_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=70, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('userimage', models.ImageField(blank=True, upload_to='')),
                ('password', models.CharField(max_length=70)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='approve',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stickerapp.user'),
        ),
        migrations.AlterField(
            model_name='like',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stickerapp.user'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stickerapp.user'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stickerapp.user'),
        ),
    ]
