# Generated by Django 4.2.2 on 2023-06-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0051_alter_pack_user_alter_pack_publisher_website_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bg_image',
            field=models.ImageField(blank=True, upload_to='bg_image'),
        ),
        migrations.AddField(
            model_name='category',
            name='titleImage',
            field=models.ImageField(blank=True, upload_to='titleImage'),
        ),
        migrations.AddField(
            model_name='category',
            name='titleImageIcon',
            field=models.ImageField(blank=True, upload_to='titleImageIcon'),
        ),
    ]
