# Generated by Django 4.1.7 on 2023-06-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0053_alter_approve_user_alter_like_user_alter_pack_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='animated_sticker_pack',
            field=models.BooleanField(default=False),
        ),
    ]
