# Generated by Django 4.1.7 on 2023-06-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0054_pack_animated_sticker_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='subcat_image',
            field=models.ImageField(blank=True, upload_to='subcat_image'),
        ),
    ]
