# Generated by Django 4.1.7 on 2023-06-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0055_sub_category_subcat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
