# Generated by Django 4.1.7 on 2023-06-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0056_pack_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
