# Generated by Django 4.1.7 on 2023-06-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0057_pack_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='isNew',
            field=models.BooleanField(default=False),
        ),
    ]
