# Generated by Django 4.1.7 on 2023-06-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0059_alter_pack_avoid_cache_alter_pack_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='bg_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='titleImageIcon',
        ),
    ]
