# Generated by Django 4.1.7 on 2023-06-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0060_remove_category_bg_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='description',
            field=models.CharField(default='Download this Amazing Pack', max_length=70),
        ),
        migrations.AddField(
            model_name='pack',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pack',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pack',
            name='watched',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
