# Generated by Django 4.1.7 on 2023-06-24 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stickerapp', '0063_rename_user_pack_user_remove_pack_likes_delete_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='watched',
        ),
        migrations.AddField(
            model_name='pack',
            name='watched',
            field=models.ManyToManyField(blank=True, related_name='watched_pack', to=settings.AUTH_USER_MODEL),
        ),
    ]
