# Generated by Django 4.1.7 on 2023-06-26 05:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stickerapp', '0064_remove_pack_watched_pack_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='downloads',
        ),
        migrations.AddField(
            model_name='pack',
            name='downloads',
            field=models.ManyToManyField(blank=True, related_name='downloads_pack', to=settings.AUTH_USER_MODEL),
        ),
    ]
