# Generated by Django 4.1.7 on 2023-07-04 04:42

from django.conf import settings
from django.db import migrations, models
import stickerapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stickerapp', '0066_alter_pack_avoid_cache_alter_pack_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='downloads',
            field=models.ManyToManyField(blank=True, related_name='downloaded_pack', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pack',
            name='publisher_website_zip',
            field=models.FileField(blank=True, upload_to=stickerapp.models.pack_directory_path),
        ),
        migrations.AlterField(
            model_name='pack',
            name='tray_image_filelink',
            field=models.ImageField(blank=True, upload_to=stickerapp.models.pack_directory_path),
        ),
        migrations.AlterField(
            model_name='stickerlist',
            name='sticker',
            field=models.FileField(upload_to=stickerapp.models.sticker_directory_path),
        ),
    ]
