# Generated by Django 4.2.2 on 2023-07-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0068_pack_bannner_image_pack_featured_image_pack_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Approve',
        ),
    ]
