# Generated by Django 4.2.2 on 2023-07-26 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0069_delete_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='religiontag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religiontag', models.CharField(max_length=70)),
                ('religionpack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stickerapp.pack')),
            ],
        ),
        migrations.CreateModel(
            name='countrytag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countrytag', models.CharField(max_length=70)),
                ('relpack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stickerapp.pack')),
            ],
        ),
    ]
