# Generated by Django 4.2.2 on 2023-09-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickerapp', '0070_religiontag_countrytag'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='pack_status',
            field=models.IntegerField(choices=[(0, 'Hide'), (1, 'Free'), (2, 'Semi_Pro'), (3, 'Pro')], default=1),
        ),
    ]
